-
  name: 'REST API'
  uriPattern: 'cleverreach/receiver'
  httpMethods: ['POST', 'PUT']
  defaults:
    '@package':    'KaufmannDigital.CleverReach'
    '@controller': 'Ajax'
    '@action':     'subscribe'
    '@format':     'html'
  appendExceedingArguments: true
